gravitee-io/gravitee-cockpit-api

src/main/java/io/gravitee/cockpit/api/command/Command.java, src/main/java/io/gravitee/cockpit/api/command/Reply.java, src/main/java/io/gravitee/cockpit/api/command/ignored/IgnoredReply.java, src/main/java/io/gravitee/cockpit/api/command/membership/MembershipCommand.java, src/main/java/io/gravitee/cockpit/api/command/membership/MembershipPayload.java, src/main/java/io/gravitee/cockpit/api/command/membership/MembershipReply.java, src/main/java/io/gravitee/cockpit/api/command/organization/OrganizationPayload.java, src/main/java/io/gravitee/cockpit/api/command/user/UserCommand.java, src/main/java/io/gravitee/cockpit/api/command/user/UserPayload.java, src/main/java/io/gravitee/cockpit/api/command/user/UserReply.java
Closes gravitee-io/issues#4292
=> feat(command): add user and membership commands

src/main/java/io/gravitee/cockpit/api/command/CommandHandler.java, src/main/java/io/gravitee/cockpit/api/command/CommandProducer.java, src/main/java/io/gravitee/cockpit/api/command/Node.java, src/main/java/io/gravitee/cockpit/api/command/hello/HelloPayload.java, src/main/java/io/gravitee/cockpit/api/command/hello/HelloReply.java
Closes gravitee-io/gravitee-cockpit#100
=> feat(): allow associate onprem installations

src/main/java/io/gravitee/cockpit/api/command/Command.java, src/main/java/io/gravitee/cockpit/api/command/Reply.java, src/main/java/io/gravitee/cockpit/api/command/hello/HelloPayload.java, src/main/java/io/gravitee/cockpit/api/command/installation/InstallationCommand.java, src/main/java/io/gravitee/cockpit/api/command/installation/InstallationPayload.java, src/main/java/io/gravitee/cockpit/api/command/installation/InstallationReply.java
Closes gravitee-io/gravitee-cockpit#162
=> feat(installation): add command to propagate installation events

src/main/java/io/gravitee/cockpit/api/command/Command.java, src/main/java/io/gravitee/cockpit/api/command/Reply.java, src/main/java/io/gravitee/cockpit/api/command/goodbye/GoodbyeCommand.java, src/main/java/io/gravitee/cockpit/api/command/goodbye/GoodbyeReply.java
Create the necessary command to delete installations in Cockpit (See #314)
=> feat(): add GoodbyeCommand for installation delete

src/main/java/io/gravitee/cockpit/api/command/Command.java, src/main/java/io/gravitee/cockpit/api/command/Reply.java, src/main/java/io/gravitee/cockpit/api/command/node/NodeCommand.java, src/main/java/io/gravitee/cockpit/api/command/node/NodePayload.java, src/main/java/io/gravitee/cockpit/api/command/node/NodePlugin.java, src/main/java/io/gravitee/cockpit/api/command/node/NodeReply.java
Add a `NodeCommand` to be able to report all nodes of an installation
=> feat(): add command to report gateway nodes

src/main/java/io/gravitee/cockpit/api/command/Command.java, src/main/java/io/gravitee/cockpit/api/command/Reply.java, src/main/java/io/gravitee/cockpit/api/command/membership/DeleteMembershipCommand.java, src/main/java/io/gravitee/cockpit/api/command/membership/DeleteMembershipPayload.java, src/main/java/io/gravitee/cockpit/api/command/membership/DeleteMembershipReply.java
Add a command that will be used by Cockpit to propagate info to installations when a member is removed from an environment or an organization.
=> Add DeleteMembership command

src/main/java/io/gravitee/cockpit/api/command/Node.java
gravitee-io/gravitee-cockpit#534
=> feat: add version & connectorVersion to node payload

src/main/java/io/gravitee/cockpit/api/command/Command.java, src/main/java/io/gravitee/cockpit/api/command/Reply.java, src/main/java/io/gravitee/cockpit/api/command/monitoring/JvmInfo.java, src/main/java/io/gravitee/cockpit/api/command/monitoring/Monitor.java, src/main/java/io/gravitee/cockpit/api/command/monitoring/MonitoringCommand.java, src/main/java/io/gravitee/cockpit/api/command/monitoring/MonitoringPayload.java, src/main/java/io/gravitee/cockpit/api/command/monitoring/MonitoringReply.java, src/main/java/io/gravitee/cockpit/api/command/monitoring/OsInfo.java, src/main/java/io/gravitee/cockpit/api/command/monitoring/ProcessInfo.java
Add a new command `MonitoringCommand`
=> feat(): add MonitoringCommand

.circleci/config.yml
Make sure we build master branch after merge
=> fix(): [CI] do not exclude master branch

src/main/java/io/gravitee/cockpit/api/command/Command.java, src/main/java/io/gravitee/cockpit/api/command/Payload.java, src/main/java/io/gravitee/cockpit/api/command/Reply.java
Related to gravitee-io/gravitee-cockpit#590
=> feat(cluster): make classes implement serializable

src/main/java/io/gravitee/cockpit/api/CockpitConnector.java, src/main/java/io/gravitee/cockpit/api/command/Command.java, src/main/java/io/gravitee/cockpit/api/command/CommandProducer.java, src/main/java/io/gravitee/cockpit/api/command/Reply.java, src/main/java/io/gravitee/cockpit/api/command/bridge/BridgeCommand.java, src/main/java/io/gravitee/cockpit/api/command/bridge/BridgeMultiReply.java, src/main/java/io/gravitee/cockpit/api/command/bridge/BridgePayload.java, src/main/java/io/gravitee/cockpit/api/command/bridge/BridgeReply.java, src/main/java/io/gravitee/cockpit/api/command/bridge/BridgeSimpleReply.java, src/main/java/io/gravitee/cockpit/api/command/bridge/BridgeTarget.java, src/main/java/io/gravitee/cockpit/api/command/environment/EnvironmentCommand.java, src/main/java/io/gravitee/cockpit/api/command/membership/MembershipPayload.java, src/main/java/io/gravitee/cockpit/api/command/monitoring/MonitoringPayload.java, src/main/java/io/gravitee/cockpit/api/command/organization/OrganizationCommand.java, src/main/java/io/gravitee/cockpit/api/command/user/UserCommand.java, src/main/java/io/gravitee/cockpit/api/command/user/UserPayload.java
Related to gravitee-io/gravitee-cockpit#591
=> feat(bridge): add BrigdeCommand

src/main/java/io/gravitee/cockpit/api/CockpitConnector.java, src/main/java/io/gravitee/cockpit/api/command/Command.java
Related gravitee-io/gravitee-cockpit#335
=> feat: handle primary/replica on connector

src/main/java/io/gravitee/cockpit/api/command/environment/EnvironmentPayload.java, src/main/java/io/gravitee/cockpit/api/command/hello/HelloReply.java, src/main/java/io/gravitee/cockpit/api/command/organization/OrganizationPayload.java
**Issue**
https://github.com/gravitee-io/issues/issues/5781
The goal of introducing these cockpit ids is to ease the management of DEFAULT env/org on APIM side when working with BridgeCommand
=> Add `cockpitId` in Environment/Organization command payload and HelloReply

src/main/java/io/gravitee/cockpit/api/command/Command.java, src/main/java/io/gravitee/cockpit/api/command/Reply.java, src/main/java/io/gravitee/cockpit/api/command/alert/trigger/create/AlertTriggerCommand.java, src/main/java/io/gravitee/cockpit/api/command/alert/trigger/create/AlertTriggerPayload.java, src/main/java/io/gravitee/cockpit/api/command/alert/trigger/create/AlertTriggerReply.java, src/main/java/io/gravitee/cockpit/api/command/alert/trigger/list/ListAlertTriggersCommand.java, src/main/java/io/gravitee/cockpit/api/command/alert/trigger/list/ListAlertTriggersReply.java
Add alert list all triggers command.
=> feat: list all triggers

src/main/java/io/gravitee/cockpit/api/command/Command.java, src/main/java/io/gravitee/cockpit/api/command/Reply.java, src/main/java/io/gravitee/cockpit/api/command/alert/notification/AlertNotificationCommand.java, src/main/java/io/gravitee/cockpit/api/command/alert/notification/AlertNotificationPayload.java, src/main/java/io/gravitee/cockpit/api/command/alert/notification/AlertNotificationReply.java
https://github.com/gravitee-io/gravitee-cockpit/issues/717
Add alert notification command
=> feat: add alert notification commande

.github/CODEOWNERS, .github/renovate.json
Setup Renovate to keep our dependencies up to date.
Override #27 as Renovate bot automatically force push in the branch of the PR 🙃 so I can't rename the commit.
=> Initialize renovate

src/main/java/io/gravitee/cockpit/api/command/designer/DeployModelPayload.java
Add labels to DeployModelPayload
=> feat: add labels in DeployModelPayload

.bin/release.sh
=> feat: add release script

pom.xml, src/main/java/io/gravitee/cockpit/api/command/Command.java, src/main/java/io/gravitee/cockpit/api/command/Reply.java, src/main/java/io/gravitee/cockpit/api/command/v4api/V4ApiCommand.java, src/main/java/io/gravitee/cockpit/api/command/v4api/V4ApiPayload.java, src/main/java/io/gravitee/cockpit/api/command/v4api/V4ApiReply.java
---
- use it directly by updating your project with version: `2.1.0-coc-340-add-trial-app-command-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-api/2.1.0-coc-340-add-trial-app-command-SNAPSHOT/gravitee-cockpit-api-2.1.0-coc-340-add-trial-app-command-SNAPSHOT.zip)
=> feat: added V4Api command, payload and reply

src/main/java/io/gravitee/cockpit/api/command/legacy/bridge/BridgeLegacyCommandAdapter.java
Fix missing information to be able to promote an API
=> fix: promote API failing

src/main/java/io/gravitee/cockpit/api/command/v1/targettoken/TargetTokenCommandPayload.java
Add scope so that can assign different roles on apim side
See comment from John here - https://gravitee.atlassian.net/browse/CJ-1874?focusedCommentId=36068
---
- use it directly by updating your project with version: `3.6.0-cj-1874-add-scope-target-token-command-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-api/3.6.0-cj-1874-add-scope-target-token-command-SNAPSHOT/gravitee-cockpit-api-3.6.0-cj-1874-add-scope-target-token-command-SNAPSHOT.zip)
=> feat: add scope to target token command payload

pom.xml, src/main/java/io/gravitee/cockpit/api/command/v1/MetadataConstants.java, src/main/java/io/gravitee/cockpit/api/command/v1/node/NodeCommandPayload.java, src/main/java/io/gravitee/cockpit/api/command/v1/node/healthcheck/NodeHealthCheckCommand.java
https://gravitee.atlassian.net/browse/CJ-2542
---
- use it directly by updating your project with version: `3.7.0-cj-2542-gateway-technical-id-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-api/3.7.0-cj-2542-gateway-technical-id-SNAPSHOT/gravitee-cockpit-api-3.7.0-cj-2542-gateway-technical-id-SNAPSHOT.zip)
=> feat: add metadata property to NodeCommandPayload

src/main/java/io/gravitee/cockpit/api/command/v1/MetadataConstants.java
https://gravitee.atlassian.net/browse/CJ-2813
---
- use it directly by updating your project with version: `3.7.12-rename-gateway-id-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-api/3.7.12-rename-gateway-id-SNAPSHOT/gravitee-cockpit-api-3.7.12-rename-gateway-id-SNAPSHOT.zip)
=> fix: remove underscore to MetadataConstants.GATEWAY_ID
