gravitee-io/gravitee-cockpit-api

- src/main/java/io/gravitee/cockpit/api/CockpitConnector.java
- src/main/java/io/gravitee/cockpit/api/command/Command.java
- src/main/java/io/gravitee/cockpit/api/command/Reply.java
- src/main/java/io/gravitee/cockpit/api/command/echo/EchoCommand.java
- src/main/java/io/gravitee/cockpit/api/command/echo/EchoPayload.java
- src/main/java/io/gravitee/cockpit/api/command/echo/EchoReply.java
**Issue**
https://github.com/gravitee-io/gravitee-cockpit/issues/323
- Added an echo command for test purpose
- Add a `sendCommand` method in `CockpitConnector` like it's done in `CockpitController` (see https://github.com/gravitee-io/gravitee-cockpit/blob/542ea6061bc6028b3ba625e2c74601ae9f4e6db2/gravitee-cockpit-controller/gravitee-cockpit-controller-api/src/main/java/com/graviteesource/cockpit/controller/api/CockpitController.java#L15)
> Add a method to send Command in `CockpitConnector`

- src/main/java/io/gravitee/cockpit/api/command/Command.java
- src/main/java/io/gravitee/cockpit/api/command/unknown/UnknownCommand.java
- src/main/java/io/gravitee/cockpit/api/command/unknown/UnknownPayload.java
It is used as a default implementation of `Command` abstract class when parsing JSON to Command with Jackson
The goal is to avoid the following error when receiving a Command that can not be parsed (for instance cockpit send new commands not handled on APIM side yet):
> Caused by: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'INSTALLATION_COMMAND' as a subtype of `io.gravitee.cockpit.api.command.Command`: known type ids = [ENVIRONMENT_COMMAND, HELLO_COMMAND, MEMBERSHIP_COMMAND, ORGANIZATION_COMMAND, USER_COMMAND]
> Command: Introduce an UnknownCommand 

- .circleci/config.yml
- pom.xml
Here provided the Circle Ci Pipeline providing the following processes : 
* The Standalone Release
* The Standalone Release Replay
* Pull Requests with nexus staging on all branch but master
* nightly snapshot build n deploy to nexus everyday at midnight
All Those Processes a documented in detail at https://github.com/gravitee-io/kb/wiki/CICD:-Cockpit-API
You will find there how to run dry run processes to test and validate this PR
> Cicd: new pipeline definition and gravitee-parent upgrade

- src/main/java/io/gravitee/cockpit/api/command/healthcheck/HealthCheckPayload.java
The outdated installations will still send an old HealthCheckPayload where `isHealthy` is not available.
To avoid dealing with a breaking change we allow `isHealthy` to be null and handle that case on Cockpit side.
> fix: allow null isHealthy property in HealthCheckPayload

- pom.xml
- src/main/java/io/gravitee/cockpit/api/command/Command.java
- src/main/java/io/gravitee/cockpit/api/command/Reply.java
- src/main/java/io/gravitee/cockpit/api/command/alert/AlertTriggerCommand.java
- src/main/java/io/gravitee/cockpit/api/command/alert/AlertTriggerPayload.java
- src/main/java/io/gravitee/cockpit/api/command/alert/AlertTriggerReply.java
Related to https://github.com/gravitee-io/gravitee-cockpit/issues/716
Create a new command for Alert Trigger create / update.
This PR adds a dependency on `gravitee-alert-api`, as the payload of this new command will be a `Trigger`, defined in the alert api.
> feat: new AlertTriggerCommand

- src/main/java/io/gravitee/cockpit/api/command/hello/HelloPayload.java
Add constants for installation type. Will be used in APIM & Cockpit
---
- use it directly by updating your project with version: `1.11.0-2536-differentiate-trial-installation-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-api/1.11.0-2536-differentiate-trial-installation-SNAPSHOT/gravitee-cockpit-api-1.11.0-2536-differentiate-trial-installation-SNAPSHOT.zip)
> feat: add constants for installation type

- .circleci/config.yml
- pom.xml
- src/main/java/io/gravitee/cockpit/api/CockpitConnector.java
- src/main/java/io/gravitee/cockpit/api/command/CommandHandler.java
- src/main/java/io/gravitee/cockpit/api/command/CommandProducer.java
https://github.com/gravitee-io/issues/issues/7990
---
- use it directly by updating your project with version: `2.0.0-bumpRxJava-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-api/2.0.0-bumpRxJava-SNAPSHOT/gravitee-cockpit-api-2.0.0-bumpRxJava-SNAPSHOT.zip)
> chore: bump to rxJava3

- pom.xml
- src/main/java/io/gravitee/cockpit/api/command/accesspoint/AccessPoint.java
- src/main/java/io/gravitee/cockpit/api/command/hello/HelloPayload.java
- src/main/java/io/gravitee/cockpit/api/command/installation/AdditionalInfoConstants.java
- add installation type
- add explicit trial boolean
- add access point template
---
- use it directly by updating your project with version: `2.3.0-feat-multi-tenancy-installation-type-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-api/2.3.0-feat-multi-tenancy-installation-type-SNAPSHOT/gravitee-cockpit-api-2.3.0-feat-multi-tenancy-installation-type-SNAPSHOT.zip)
> feat: add new attributes to HelloPayload

- src/main/java/io/gravitee/cockpit/api/command/organization/OrganizationPayload.java
https://gravitee.atlassian.net/browse/APIM-3556
Update organization command payload to provide organization license as base64.
---
- use it directly by updating your project with version: `2.4.0-apim-3556-update-license-command-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-api/2.4.0-apim-3556-update-license-command-SNAPSHOT/gravitee-cockpit-api-2.4.0-apim-3556-update-license-command-SNAPSHOT.zip)
> feat: update organization command payload to add license

- pom.xml
- src/main/java/io/gravitee/cockpit/api/command/Command.java
- src/main/java/io/gravitee/cockpit/api/command/Reply.java
- src/main/java/io/gravitee/cockpit/api/command/installation/UnlinkInstallationCommand.java
- src/main/java/io/gravitee/cockpit/api/command/installation/UnlinkInstallationPayload.java
- src/main/java/io/gravitee/cockpit/api/command/installation/UnlinkInstallationReply.java
https://gravitee.atlassian.net/browse/APIM-3590
---
- use it directly by updating your project with version: `2.5.0-feat-add-unlink-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-api/2.5.0-feat-add-unlink-SNAPSHOT/gravitee-cockpit-api-2.5.0-feat-add-unlink-SNAPSHOT.zip)
> feat: add unlink installation command

- src/main/java/io/gravitee/cockpit/api/command/Command.java
- src/main/java/io/gravitee/cockpit/api/command/Reply.java
- src/main/java/io/gravitee/cockpit/api/command/accesspoint/AccessPoint.java
- src/main/java/io/gravitee/cockpit/api/command/environment/DisableEnvironmentCommand.java
- src/main/java/io/gravitee/cockpit/api/command/environment/DisableEnvironmentPayload.java
- src/main/java/io/gravitee/cockpit/api/command/environment/DisableEnvironmentReply.java
- src/main/java/io/gravitee/cockpit/api/command/organization/DisableOrganizationCommand.java
- src/main/java/io/gravitee/cockpit/api/command/organization/DisableOrganizationPayload.java
- src/main/java/io/gravitee/cockpit/api/command/organization/DisableOrganizationReply.java
**Issue**
https://gravitee.atlassian.net/browse/CJ-996
Add two new commands to handle disabling Environments and Organizations
---
- use it directly by updating your project with version: `2.6.0-cj-996-add-disable-commands-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-api/2.6.0-cj-996-add-disable-commands-SNAPSHOT/gravitee-cockpit-api-2.6.0-cj-996-add-disable-commands-SNAPSHOT.zip)
> feat: add commands to disable environment and organization

- pom.xml
Upgrade all gravitee dependencies to their latest versions
---
- use it directly by updating your project with version: `2.6.1-chore-upgrade-gravitee-deps-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-api/2.6.1-chore-upgrade-gravitee-deps-SNAPSHOT/gravitee-cockpit-api-2.6.1-chore-upgrade-gravitee-deps-SNAPSHOT.zip)
> fix(deps): upgrade gravitee dependencies

- pom.xml
---
- use it directly by updating your project with version: `3.0.2-bump-exchange-framework-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-api/3.0.2-bump-exchange-framework-SNAPSHOT/gravitee-cockpit-api-3.0.2-bump-exchange-framework-SNAPSHOT.zip)
> fix: use latest exchange framework

- src/main/java/io/gravitee/cockpit/api/command/legacy/healthcheck/HealthCheckCommand.java
- src/main/java/io/gravitee/cockpit/api/command/legacy/node/NodeCommand.java
---
- use it directly by updating your project with version: `3.0.7-fix-legacy-serialization-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-api/3.0.7-fix-legacy-serialization-SNAPSHOT/gravitee-cockpit-api-3.0.7-fix-legacy-serialization-SNAPSHOT.zip)
> fix: add missing empty constructor on legacy command

- src/main/java/io/gravitee/cockpit/api/command/legacy/bridge/BridgeLegacyMultiReplyAdapter.java
- src/main/java/io/gravitee/cockpit/api/command/legacy/bridge/BridgeLegacySimpleReplyAdapter.java
- src/main/java/io/gravitee/cockpit/api/command/legacy/bridge/BridgeReplyAdapter.java
- src/main/java/io/gravitee/cockpit/api/command/legacy/bridge/BridgeSimpleReply.java
- src/main/java/io/gravitee/cockpit/api/command/v1/bridge/BridgeReplyPayload.java
---
- use it directly by updating your project with version: `3.0.14-handle-simple-in-error-reply-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-api/3.0.14-handle-simple-in-error-reply-SNAPSHOT/gravitee-cockpit-api-3.0.14-handle-simple-in-error-reply-SNAPSHOT.zip)
> fix: create an error simple reply in case of bridge reply in error

- pom.xml
---
- use it directly by updating your project with version: `3.0.41-archi-391-enable-exchange-endpoint-metrics-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-api/3.0.41-archi-391-enable-exchange-endpoint-metrics-SNAPSHOT/gravitee-cockpit-api-3.0.41-archi-391-enable-exchange-endpoint-metrics-SNAPSHOT.zip)
> fix: bump exchange framework version

- pom.xml
https://gravitee.atlassian.net/browse/ARCHI-391
See https://github.com/gravitee-io/gravitee-exchange/blob/main/CHANGELOG.md#182-2024-07-26
> fix: bump exchange framework to 1.8.2

- pom.xml
As non provided cause some issue on APIM when the versions of `gravitee-exchange-api` aren't aligned.
https://gravitee.atlassian.net/browse/APIM-6226
---
- use it directly by updating your project with version: `3.0.51`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-api/3.0.51/gravitee-cockpit-api-3.0.51.zip)
> chore(deps): declare gravitee-exchange-api as provided

- pom.xml
- src/main/java/io/gravitee/cockpit/api/command/v1/scoring/request/ScoringRequestCommand.java
- src/main/java/io/gravitee/cockpit/api/command/v1/scoring/request/ScoringRequestCommandPayload.java
- src/main/java/io/gravitee/cockpit/api/command/v1/scoring/request/ScoringRequestReply.java
- src/main/java/io/gravitee/cockpit/api/command/v1/scoring/response/ScoringResponseCommand.java
- src/main/java/io/gravitee/cockpit/api/command/v1/scoring/response/ScoringResponseCommandPayload.java
- src/main/java/io/gravitee/cockpit/api/command/v1/scoring/response/ScoringResponseReply.java
- src/main/java/io/gravitee/cockpit/api/command/websocket/CockpitExchangeSerDe.java
**Issue**
https://gravitee.atlassian.net/browse/APIM-5164
[ADR](https://gravitee.slab.com/posts/api-scoring-ri6xqojg)
Implement commands to handle Scoring feature in APIM.
- `ScoringRequestCommand` is sent by APIM to trigger the scoring of a list of Assets. Cockpit will forward this request to Scoring providers.
- `ScoringResponseCommand` is sent by Cockpit once it has received and merge responses from Scoring providers.
Pre-requisite: https://github.com/gravitee-io/gravitee-scoring-api/pull/3
---
- use it directly by updating your project with version: `3.1.0-apim5164-SNAPSHOT`
- download it from Artifactory …
> feat: add scoring service request and response command

- pom.xml
---
- use it directly by updating your project with version: `3.2.3-apim6648-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-api/3.2.3-apim6648-SNAPSHOT/gravitee-cockpit-api-3.2.3-apim6648-SNAPSHOT.zip)
> fix(deps): update gravitee-scoring-api to 0.3.0

- pom.xml
- src/main/java/io/gravitee/cockpit/api/command/v1/specgen/SpecGenCommandPayload.java
- src/main/java/io/gravitee/cockpit/api/command/v1/specgen/SpecGenReplyPayload.java
- src/main/java/io/gravitee/cockpit/api/command/v1/specgen/request/SpecGenRequestCommand.java
- src/main/java/io/gravitee/cockpit/api/command/v1/specgen/request/SpecGenRequestReply.java
- src/main/java/io/gravitee/cockpit/api/command/websocket/CockpitExchangeSerDe.java
This PR contains all the necessary commands for spec-gen requests
---
- use it directly by updating your project with version: `3.3.0-feat-SAT-77-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-api/3.3.0-feat-SAT-77-SNAPSHOT/gravitee-cockpit-api-3.3.0-feat-SAT-77-SNAPSHOT.zip)
> feat: SpecGenRequest command api

- pom.xml
- src/main/java/io/gravitee/cockpit/api/command/v1/specgen/response/SpecGenResponseCommand.java
- src/main/java/io/gravitee/cockpit/api/command/v1/specgen/response/SpecGenResponseReply.java
- src/main/java/io/gravitee/cockpit/api/command/websocket/CockpitExchangeSerDe.java
Issue:
https://gravitee.atlassian.net/browse/SAT-133
This PR brings interfaces for spec gen command response and reply
---
- use it directly by updating your project with version: `3.4.0-feat-SAT-133-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-api/3.4.0-feat-SAT-133-SNAPSHOT/gravitee-cockpit-api-3.4.0-feat-SAT-133-SNAPSHOT.zip)
> feat: spec gen response command and reply

- src/main/java/io/gravitee/cockpit/api/command/v1/targettoken/TargetTokenCommand.java
- src/main/java/io/gravitee/cockpit/api/command/v1/targettoken/TargetTokenCommandPayload.java
- src/main/java/io/gravitee/cockpit/api/command/v1/targettoken/TargetTokenReply.java
- src/main/java/io/gravitee/cockpit/api/command/v1/targettoken/TargetTokenReplyPayload.java
https://gravitee.atlassian.net/browse/CJ-2539
Command for target token creation for cloud token
APIM command handler here - https://github.com/gravitee-io/gravitee-api-management/pull/9732
---
- use it directly by updating your project with version: `3.5.0-cj-2539-target-token-command-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-api/3.5.0-cj-2539-target-token-command-SNAPSHOT/gravitee-cockpit-api-3.5.0-cj-2539-target-token-command-SNAPSHOT.zip)
> Target token create command and reply

- src/main/java/io/gravitee/cockpit/api/command/websocket/CockpitExchangeSerDe.java
https://gravitee.atlassian.net/browse/CJ-2616
Add missing target token types 
---
- use it directly by updating your project with version: `3.6.2-cj-2616-fix-target-token-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-api/3.6.2-cj-2616-fix-target-token-SNAPSHOT/gravitee-cockpit-api-3.6.2-cj-2616-fix-target-token-SNAPSHOT.zip)
> fix: add target token types

- src/main/java/io/gravitee/cockpit/api/command/model/accesspoint/AccessPoint.java
https://gravitee.atlassian.net/browse/APIM-7134
Add 2 additional tragget types so that APIM can send the template to be completed by cokpit
---
- use it directly by updating your project with version: `3.8.0-APIM-7134-kafka-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-api/3.8.0-APIM-7134-kafka-SNAPSHOT/gravitee-cockpit-api-3.8.0-APIM-7134-kafka-SNAPSHOT.zip)
> feat: add Target AccessPoint for Kafka & Tcp gateway

- src/main/java/io/gravitee/cockpit/api/command/v1/newtai/elgen/ELCommand.java
- src/main/java/io/gravitee/cockpit/api/command/v1/newtai/elgen/ELCommandPayload.java
- src/main/java/io/gravitee/cockpit/api/command/v1/newtai/elgen/ELReply.java
- src/main/java/io/gravitee/cockpit/api/command/v1/newtai/elgen/ELReplyPayload.java
- src/main/java/io/gravitee/cockpit/api/command/websocket/CockpitExchangeSerDe.java
https://gravitee.atlassian.net/browse/APIM-9966
Create a new command that allows an expression language to be prompted through the cockpit.
---
- use it directly by updating your project with version: `3.9.0-apim-9966-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-api/3.9.0-apim-9966-SNAPSHOT/gravitee-cockpit-api-3.9.0-apim-9966-SNAPSHOT.zip)
---
- use it directly by updating your project with version: …
> feat: add command for expression langage generation

- src/main/java/io/gravitee/cockpit/api/command/v1/targettoken/DeleteTargetTokenCommand.java
- src/main/java/io/gravitee/cockpit/api/command/v1/targettoken/DeleteTargetTokenCommandPayload.java
- src/main/java/io/gravitee/cockpit/api/command/v1/targettoken/DeleteTargetTokenReply.java
- src/main/java/io/gravitee/cockpit/api/command/v1/targettoken/DeleteTargetTokenReplyPayload.java
- src/main/java/io/gravitee/cockpit/api/command/websocket/CockpitExchangeSerDe.java
https://gravitee.atlassian.net/browse/CJ-3450
---
- use it directly by updating your project with version: `3.11.0-cj-3183-delete-cloud-token-SNAPSHOT`
- download it from Artifactory [here](https://odbxikk7vo-artifactory.services.clever-cloud.com/gravitee-snapshots/io/gravitee/cockpit/gravitee-cockpit-api/3.11.0-cj-3183-delete-cloud-token-SNAPSHOT/gravitee-cockpit-api-3.11.0-cj-3183-delete-cloud-token-SNAPSHOT.zip)
> feat: add delete target token command
